stages:
  - build
  - deploy

variables:
  CI_REGISTRY: gitlab.flextech.asia:5050
  IMAGE_TAG: $CI_REGISTRY/buiphan/os-api-core:$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - echo $IMAGE_TAG-$CI_COMMIT_SHORT_SHA
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - DOCKER_BUILDKIT=1 docker build -t $IMAGE_TAG -f dockerfiles/Prod/Dockerfile .
    - docker push $IMAGE_TAG
  only:
    - develop
    - master

deploy_develop:
  stage: deploy
  script:
    - curl -XPOST $WWW_WEBHOOK
  environment:
    name: develop
  only:
    - develop
